### ISSUE TITLE
README misses required dependency: libpcap0.8-dev

### ISSUE THREAD

**Issue by skleber** [netzob/netzob#106]
On executing setup.py compilation of pcap importer parts fails with missing `pcap.h`-file.

Debian, e. g., provides the required header file in package libpcap0.8-dev.

**Comment by ProLoDs** [comment]
confirmed.

**Comment by Sygus** [comment]
we now use pcapy-ng==1.0.9
pcapy-ng==1.0.9 has been added to setup.py file
