### ISSUE TITLE
ImpactPacket.ARP and ARPDecoder are missing

### ISSUE THREAD

**Issue by skleber** [netzob/netzob#107]
Lines 68 to 70 in ImpactDecoder call `ImpactPacket.ARP` and `ARPDecoder` in next and master branches, but both Classes are missing  in netzob/Import/PCAPImporter.

**Comment by skleber** [comment]
There is another reference in lines 93/94 of the same file.

**Comment by Sygus** [comment]
Impacket is now used again in latest version (2.0.0)
