### ISSUE TITLE
from werkzeug.contrib.cache import (nullcache, simplecache, memcachedcache, importerror: cannot import name 'uwsgicache'

### ISSUE THREAD

**Issue by yasong** [netzob/netzob#110]
from werkzeug.contrib.cache import (nullcache, simplecache, memcachedcache, import error: cannot import name '**uwsgicache**'
The werkzeug version is not suitable for netzob_web. To address this problem, you need to upgrade the werkzeug, use$`pip3 install werkzeug --upgrade`.

**Comment by Sygus** [comment]
netzob_web has been removed from this repository, and is now in a private dedicated repository as it is not maintained anymore. If someone wants to have a look, or try to update/maintain it, send us a comment :)

The latest public version of netzob_web is available here: https://github.com/netzob/netzob/tree/394f4409fb228fd85331b0e93001ff34bba2008b
