### ISSUE TITLE
[netzob_web]  404 for static files

### ISSUE THREAD

**Issue by ProLoDs** [netzob/netzob#111]
Hi,
i get a 404 for the following requests: 
```
GET http://127.0.0.1:5000/static/libs/datatables.net/js/jquery.dataTables.min.js 
GET http://127.0.0.1:5000/static/libs/datatables.net-select/js/dataTables.select.min.js 
GET http://127.0.0.1:5000/static/libs/jpillora/jquery.rest/dist/1/jquery.rest.min.js 
```
fixed by adding the js files from : https://datatables.net
and from https://github.com/jpillora/jquery.rest
Greetings

**Comment by Sygus** [comment]
netzob_web has been removed from this repository, and is now in a private dedicated repository as it is not maintained anymore. If someone wants to have a look, or try to update/maintain it, send us a comment :)

The latest public version of netzob_web is available here: https://github.com/netzob/netzob/tree/394f4409fb228fd85331b0e93001ff34bba2008b
