### ISSUE TITLE
[netzob_web] Access-Control-Allow-Origin Header missing

### ISSUE THREAD

**Issue by ProLoDs** [netzob/netzob#112]
Hi,
the Access-Control-Allow-Origin header for the following URLs is missing
```
http://localhost:5000/api/p/1/symbols/
http://localhost:5000/api/p/1/captures/.
```
Workaround: access it via localhost, indead of 127.0.0.1 or ::1
Greetings

**Comment by Sygus** [comment]
netzob_web has been removed from this repository, and is now in a private dedicated repository as it is not maintained anymore. If someone wants to have a look, or try to update/maintain it, send us a comment :)

The latest public version of netzob_web is available here: https://github.com/netzob/netzob/tree/394f4409fb228fd85331b0e93001ff34bba2008b
