### ISSUE TITLE
netzob interface

### ISSUE THREAD

**Issue by Destiny6** [netzob/netzob#135]
Does netzob have an interface?

**Comment by shusain93** [comment]
Check out netzob_web, it's a folder in the root of the repo

**Comment by Sygus** [comment]
Netzob is expected to be used as a library in scripts or other packages.

netzob_web has been removed from this repository, and is now in a private dedicated repository as it is not maintained anymore. If someone wants to have a look, or try to update/maintain it, send us a comment :)

The latest public version of netzob_web is available here: https://github.com/netzob/netzob/tree/394f4409fb228fd85331b0e93001ff34bba2008b
