### ISSUE TITLE
Missing pip dependancies in requirements.txt

### ISSUE THREAD

**Issue by sne4ky** [netzob/netzob#144]
Missing numpy, wheel, and flask_restplus in requirements.txt, for the web interface.

Also, version of werkzeug is outdated. Need to upgrade to at least version Werkzeug==0.14.1.

**Comment by Sygus** [comment]
netzob_web has been removed from this repository, and is now in a private dedicated repository as it is not maintained anymore. If someone wants to have a look, or try to update/maintain it, send us a comment :)

The latest public version of netzob_web is available here: https://github.com/netzob/netzob/tree/394f4409fb228fd85331b0e93001ff34bba2008b
