### ISSUE TITLE
PCAPImporter's definition of network layers is shifted by one

### ISSUE THREAD

**Issue by skleber** [netzob/netzob#150]
The generation of layered message objects erroneously shifts the payload compared to the correct definition by an offset of one network layer in `PCAPImporter.__packetHandler()` for the arguments
* layer=2 : `L2NetworkMessage`
* layer=3 : `L3NetworkMessage` and
* layer=4 : `L4NetworkMessage`

**Comment by Sygus** [comment]
Thanks a lot skleber, your PR has been merged into master.
