### ISSUE TITLE
the version 0.4 PCAPImporter couldn't show the right type

### ISSUE THREAD

**Issue by youcancallmeely** [netzob/netzob#154]
when I choose the .pcap to have a try .but it showed the wrong type as "Delimiter Seperated File".I don't  know how to solve this problem .

**Comment by youcancallmeely** [comment]
`WARNING:root:The current executed python code has not been built using setup.py, hence it's not possible to compare the BID of executed libs.
src/netzob/NetzobMainController.py:41: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk
src/netzob/ExternalLibs/xdot.py:37: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Pango, PangoCairo
DEBUG:root:  Local configuration file used: /home/yuan3/.netzob
DEBUG:root:  Workspace path declared in configuration file: /home/yuan3/Netzob
DEBUG:root:  Workspace R/W access is valid: /home/yuan3/Netzob
DEBUG:root:+ Load workspace...
DEBUG:root:  Workspace configuration file found: /home/yuan3/Netzob/workspace.xml
DEBUG:root:  Workspace configuration file /home/yuan3/Netzob/workspace.xml is valid against XSD scheme ./resources/static/netzob/xsds/0.1/Workspace.xsd
DEBUG:root:Bug reporter disabled.
DEBUG:root:Logging config file: /home/yuan3/Netzob/logging/logging.conf
[MainThread]2019-03-01 04:07:25,642 - DepCheck - WARNING - The current executed python code has not been built using setup.py, hence it's not possible to compare the BID of executed libs.
[MainThread]2019-03-01 04:07:25,643 - NetzobMainController - INFO - Starting netzob UI
[MainThread]2019-03-01 04:07:25,679 - NetzobPlugin - ERROR - Impossible to load plugin declared in entrypoint NetworkCapturer = NetworkCapturer.NetworkCapturerPlugin:NetworkCapturerPlugin : (ldap3 2.5.2 (/usr/local/lib/python2.7/dist-packages/ldap3-2.5.2-py2.7.egg), Requirement.parse('ldap3==2.5.1'), set(['ldapdomaindump']))
Traceback (most recent call last):
  File "src/netzob/Common/Plugins/NetzobPlugin.py", line 178, in loadPlugins
    plugin_class = entrypoint.load()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2345, in load
    self.require(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2368, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (ldap3 2.5.2 (/usr/local/lib/python2.7/dist-packages/ldap3-2.5.2-py2.7.egg), Requirement.parse('ldap3==2.5.1'), set(['ldapdomaindump']))
[MainThread]2019-03-01 04:07:25,723 - NetzobPlugin - ERROR - Impossible to load plugin declared in entrypoint PCAPImporter = PCAPImporter.PCAPImporterPlugin:PCAPImporterPlugin : (ldap3 2.5.2 (/usr/local/lib/python2.7/dist-packages/ldap3-2.5.2-py2.7.egg), Requirement.parse('ldap3==2.5.1'), set(['ldapdomaindump']))
Traceback (most recent call last):
  File "src/netzob/Common/Plugins/NetzobPlugin.py", line 178, in loadPlugins
    plugin_class = entrypoint.load()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2345, in load
    self.require(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2368, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (ldap3 2.5.2 (/usr/local/lib/python2.7/dist-packages/ldap3-2.5.2-py2.7.egg), Requirement.parse('ldap3==2.5.1'), set(['ldapdomaindump']))
[MainThread]2019-03-01 04:07:25,923 - Project - ERROR - /home/yuan3/Netzob/projects/fae1be0e-9911-4554-8122-2a29d85b0e37/config.xml:1:1:FATAL:PARSER:ERR_DOCUMENT_EMPTY: Document is empty
[MainThread]2019-03-01 04:07:25,923 - Project - WARNING - The project declared in file (/home/yuan3/Netzob/projects/fae1be0e-9911-4554-8122-2a29d85b0e37/config.xml) is not valid

As you can see from the 0.4.1 version ,when I run netzob ,there is several mistakes and I'm  looking  forward  to solve  them .I need help ,thanks mate!

**Comment by Sygus** [comment]
Version 0.4.1 is not supported anymore. You should jump to latest version (currently 2.0.0). Especially, the Config XML import feature has been removed from the project.

**Comment by youcancallmeely** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
