### ISSUE TITLE
netzob.org is down

### ISSUE THREAD

**Issue by tatref** [netzob/netzob#158]
Hi,

The Wordpress site at netzob.org is empty
It seems that it hosted some interesting tutorials/guide.

Is there a copy somewhere?
Also, there's still a lot of links to dev.netzob.org in this repo, and this site does not exist anymore.

**Comment by r4bit999** [comment]
how did you solved it or can you provide the data from the site?

**Comment by tatref** [comment]
No, I could no get it

There's some things save at web archive, but most is not usable
https://web.archive.org/web/20150323075551/https://dev.netzob.org/projects/netzob/wiki

There's also some code samples here (french)
https://connect.ed-diamond.com/MISC/MISCHS-007/Vivisection-de-protocoles-avec-Netzob

**Comment by ShinjiLE** [comment]
Now there is only a trash spam page at this url. To bad. 
Someone should change or clear the url on the github page .

**Comment by comradekingu** [comment]
That means the translation platform is also unreachable.

**Comment by Sygus** [comment]
Indeed, the domain netzob.org is not linked anymore with this project.
The new documentation is now available here: https://netzob.github.io/netzob/
