### ISSUE TITLE
Cannot export to peach pit

### ISSUE THREAD

**Issue by dcnoren** [netzob/netzob#17]
Hi,

I cannot export to peachpit. Installed 0.4.1 today using the .deb, installed using dpkg. No known un-met dependencies. Installed on Kali, which is Debian-based. When I try to export, nothing happens, but the console I used to start netzob shows the attached error.

![error](https://cloud.githubusercontent.com/assets/3228595/11047944/0bcf80ba-8703-11e5-88b2-950a1583a0d3.png)

**Comment by futhewo** [comment]
Hi,

I have a problem replaying your issue. I think we do not have the same python-gtk/gtk version. Mine is from the repository (classic debian wheezy) (python-gtk 2.24.0-3) and it works fine.
Anyway, I think the following patch should solve the problem above:
modify the file /usr/lib/python2.7/dist-packages/PeachExporter/PeachExportView.py and remove the ", buttons=None" line 56. Then restart netzob.

**Comment by Sygus** [comment]
As this bug concerns an obsolete version of Netzob, I close it.

The current version (master or next branch) provides only a command line / scripting API.
Besides, the Peach exporter is not available anymore. If someone wants to leverage the new API to provide a Peach exporter, he will be very welcomed !
