### ISSUE TITLE
GUI doesn't start

### ISSUE THREAD

**Issue by GauthamGoli** [netzob/netzob#28]
./netzob doesn't start the GUI but gives the python interpreter. Opening that file the following lines are commented.

 # Launch the GUI or the plugin manager
    # if commandLineParser.isStartGUIRequested():
    #     GObject.threads_init()  # for handling concurrent GUI access from threads
    #     from netzob.NetzobMainController import NetzobMainController
    #     netzobController = NetzobMainController()
    #     netzobController.run()
    # # Display the management of plugins
    # elif commandLineParser.isManagePluginsRequested():
    #     from netzob.NetzobPluginManagement import NetzobPluginManagement
    #     netzobPluginManagement = NetzobPluginManagement(commandLineParser)
    #     netzobPluginManagement.start()
    # # Launch the interactive session
    # elif commandLineParser.isInteractiveConsoleRequested():
    #     from netzob.NetzobInteractiveSessionController import NetzobInteractiveSessionController
    #     interactiveSession = NetzobInteractiveSessionController()
    #     interactiveSession.start()

Removing the # leads to some import errors. 
How to start the GUI?

**Comment by violentinternet** [comment]
The version 0.4.1 had a GUI, which was dropped in the current release. Version 1.0rc1 respectively the code in the git repo comes without a GUI. It is a cmd interpreter/lib.

**Comment by Silur** [comment]
Then you should update the documentation on your website because now nobody knows how to export a peach fuzzer config from the command line, it hads_only_ documentation on how to make it from the GUI :-1:

**Comment by vdun** [comment]
Any news about the GUI ?

**Comment by GauthamGoli** [comment]
There is no GUI. Whatever can be done through GUI previously, can be done through the API. 
Access the documentation [here](http://doc.netzob.org/en/latest/overview/index.html)

**Comment by Sygus** [comment]
Only command line / scripting is available for the current version.

If time and resources permitted, a GUI version is conceivable in the future ;)
