### ISSUE TITLE
 Results of Sequence Alignment (only) in Combination with Clustering not Determenistic 

### ISSUE THREAD

**Issue by disasmwinnie** [netzob/netzob#30]
Function splitAlinged() works as expected. When using clusterByAlignment() the results often (if not always) vary.  Afaik Netzob uses results of Needleman-Wunsch logarithm as a score for UPGMA (correct me if I'm wrong). Does the alignment inside the symbols happening in a separate step or is the score of the first computation being used for splitting too?

The following example does demonstrate it kinda extremly. When I noticed that last week I used a small trace with a proprietary protocol which ended up in two symbols. The second symbol was always the same while the alignment/spliting inside the first symbol was skipped occasionally. Trying the same trace and script on the machine with a different distro of a colleague resulted in whole different overall alignment then mine. 

**To reproduce the issue**: 

``` bash
$ wget "https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=pgsql.cap.gz" -O pgsql.cap.gz
$ gunzip pgsql.cap.gz
# there are some TCP packets in between you want to get rid of
$ tshark -r pgsql.cap -Y pgsql -w pgsql_filtered.pcap 
```

Then run tests:

``` python
from netzob.all import *                                                          

messages = PCAPImporter.readFile('pgsql_filtered.pcap').values()                  


for i in range(0,50):                                                             
    f = open("result_{0!s}.txt".format(i), 'w')                                   
    symbols = Format.clusterByAlignment(messages, minEquivalence=35, internalSlick=True)
    for symbol in symbols:                                                         
        f.write(str(symbol))                                                      
    # This works like expected:                                                   
    #symbol = Symbol(messages=messages)                                           
    #Format.splitAligned(symbol, doInternalSlick=True)                            
    #f.write(str(symbol))                                                         
    f.close()
```

Afterwards compare the output files

``` bash
$ du -b result_*
21219   result_0.txt
22003   result_10.txt
22351   result_11.txt
[...]
vimdiff result_{10,11}.txt
```

**Comment by gbossert** [comment]
I can reproduce this issue.

> Afaik Netzob uses results of Needleman-Wunsch logarithm as a score for UPGMA

Yes

> Does the alignment inside the symbols happening in a separate step or is the score of the first computation being used for splitting too?

If I remember well, we compute the best alignment between two messages (or cluster of messages). This alignment is then used to find the similarity score which is then inserted in the UPGMA initialization matrix. Then we perform a UPGMA clustering process.

**Comment by Sygus** [comment]
Should be resolved by https://github.com/netzob/netzob/pull/129
