### ISSUE TITLE
The tutorial is still python2, but the tool is now compiled by python3

### ISSUE THREAD

**Issue by liangdzou** [netzob/netzob#72]
I just checked the tutorial in netzob/doc/documentation/source/tutorials/discover_features.rst, and find out that the tutorial is still python2. To be run in python3, the parameter of print function should be put in parathesis. And, the xrange is now range.

Meanwhile, the type checking function in "src/netzob/Common/Utils/Decorators.py" around line 181 is too strict. I have to remove the check to run the tutorial.

**Comment by gbossert** [comment]
Thank you for reporting this python3 issue.
Related to the "type checking function", can you provide which function call ⋅ in the tutorial ⋅ failed because of the type checker ?

**Comment by liangdzou** [comment]
I will check it in my computer in lab tomorrow and add the info then. :-)

**Comment by liangdzou** [comment]
I have dug into your code. It seems that the the type of symbols.values() becomes "collections.abc.ValuesView" but the check is still trying to get a list. This error exists for many functions.

I would like to help if you let me.

**Comment by gbossert** [comment]
Nice findings ! 
Please, feel free to submit your PR that correct this. Don't focus on the Grammatical related functions of Netzob( `/src/netzob/Model/Grammar`) which will be refactored in the next days.
Thank you for your work.

**Comment by liangdzou** [comment]
This issue is solved by updating the tutorial, i.e. the user should be aware of the difference about python2 and python3.
