### ISSUE TITLE
Symbol is not printed correctly

### ISSUE THREAD

**Issue by liangdzou** [netzob/netzob#80]
After I split the messages by using Format.splitDelimiter function, the resulted symbol cannot be printed because of an error.

This is how it is called.

![image](https://cloud.githubusercontent.com/assets/1409883/24575459/c64ed38a-16d8-11e7-9d55-52014a502191.png)

This is the error message.

![image](https://cloud.githubusercontent.com/assets/1409883/24575465/de645b84-16d8-11e7-88b5-372103bcaf01.png)

I read the related code and found out that it can be correctly printed if I remove "decode('utf-8')" in line 186. It seems that it is not always utf-8 string. **May I ask why the decode is needed?**

![image](https://cloud.githubusercontent.com/assets/1409883/24575455/ac3fd7b4-16d8-11e7-98c1-7feac27b9f78.png)

**Comment by gbossert** [comment]
Unfortunately, IMHO this decode function is mandatory to convert bytes to string. However, we should support multiple encoding and not limit ourselves to utf-8. Can you provide the messages that raises the error so that I can use them as tests ?

**Comment by liangdzou** [comment]
Yeah. I agree with you. If we have to print a string, we have to decode it to a string.
But, I think it is very hard to predict the character set perfectly.
It would be much simple if we only provide the bytes list presentation, or give a parameter to choose the character set.

The following is the pcap file.
[msg.pcap.zip](https://github.com/netzob/netzob/files/887501/msg.pcap.zip)

**Comment by liangdzou** [comment]
The is the error info, which fails in decode the message.
![image](https://cloud.githubusercontent.com/assets/1409883/24593433/f4f1f946-1855-11e7-9b5f-227dac8fead1.png)

After I remove the decode function, the follow is the result. I think this is acceptable. It simply print out the bytes in the list.

![image](https://cloud.githubusercontent.com/assets/1409883/24593441/0bde808e-1856-11e7-824a-d2420477d6a4.png)

**Comment by gbossert** [comment]
Agreed. If we don't know the encoding we should not try to guess it. Unfortunately, users may believe the prefix `b'` and the suffix `'` participate in the message definition. Even if I really don't like such approach, what do you thing of removing them from the display ? 
Anyway, can you provide a PR that includes the removal of the utf-8 encoding ? You might be forced to correct few doc-tests.

**Comment by gbossert** [comment]
@liangdzou could you base your modifications on my branch https://github.com/gbossert/netzob/tree/issue/symbol_not_printed_correctly which includes a doctest that currently fails because of the issue you identified. I leveraged your pcap file to achieve this.

**Comment by liangdzou** [comment]
@gbossert Sure. :-)
