### ISSUE TITLE
Adding support for user specified automata?

### ISSUE THREAD

**Issue by liangdzou** [netzob/netzob#99]
As far as I know, the current implementation of automata learning in netzob is quite primitive, where only three types of automata are supported, i.e., chained states automata, one state automata, and PTA automata. This will not be enough for real world cases.

I understand that it is not so easy to learn accurate automata from PCAP files. However, do you guys think it would be better if we give the users an API to specify/modify the automata?

AFAIK, many protocol Fuzzers, such as Sulley and Peach, allow users to specify automata.

**Comment by liangdzou** [comment]
It seems that the vocabulary and grammar can be defined by manually initialize an object. If so, we can close this issue.

**Comment by gbossert** [comment]
Yes, the state machine of your protocol can be defined manually as illustrated in this example: https://github.com/netzob/netzob/blob/master/netzob/src/netzob/Model/Grammar/Automata.py#L52.

Besides, chained states automata, one state automata and PTA automata, Netzob also enables an advanced grammatical inference technique : L* which can be use to infer IOAutomata (such as Mealy Machines).
Unfortunately, its usage is still poorly documented but I will try to improve it in this release.

**Comment by liangdzou** [comment]
Can you show me the code for L* algorithm? I am quite interested in this part.

**Comment by gbossert** [comment]
I cleaned the L* implementation and published it in its own python package because I needed it for another tool: https://github.com/gbossert/pylstar.

**Comment by gbossert** [comment]
Current implementation is here : https://github.com/netzob/netzob/tree/master/netzob/src/netzob/Inference/Grammar but prefer the one in pylstar as it's clearer and cleaner (and much more stable).

**Comment by liangdzou** [comment]
Really. IMO, passive learning may be better than L*. How can you choose the teachers?

**Comment by gbossert** [comment]
IMHO : Passive techniques should be considered if active techniques cannot apply. The teacher is an implementation of the protocol you target. I successfully applied such technique on multiple protocols including Botnet protocols, SMB/FTP and HTTP2.

**Comment by liangdzou** [comment]
Do you have detailed information about this?

**Comment by gbossert** [comment]
You can refer to this http://www.theses.fr/2014SUPL0027 ;)
